import { StyleSheet } from 'react-native';
import { spacing } from '../../theme/spacing';
import { typography } from '../../theme/typography';

export const createStyles = (colors) => StyleSheet.create({
  bubble: {
    position: 'absolute',
    right: 18,
    zIndex: 20,
    minWidth: 62,
    height: 62,
    paddingHorizontal: 11,
    borderRadius: 24,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.32,
    shadowRadius: 12,
    elevation: 10,
  },
  bubbleLabel: { color: colors.white, fontSize: 10, fontWeight: '800', marginTop: 1 },
  sparkle: {
    position: 'absolute',
    right: -3,
    top: -5,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sparkleText: { color: '#5A4612', fontSize: 14, fontWeight: '900' },
  pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] },
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(15, 17, 32, 0.58)' },
  panel: {
    maxHeight: '88%',
    minHeight: '52%',
    backgroundColor: colors.background,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingTop: spacing.sm,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.18,
    shadowRadius: 22,
    elevation: 24,
  },
  catPeek: {
    position: 'absolute',
    right: -1,
    top: 132,
    width: 120,
    height: 150,
    overflow: 'hidden',
    zIndex: 3,
  },
  catPeekImage: { width: 190, height: 190, marginTop: 0, marginLeft: -25 },
  dragArea: { height: 42, alignItems: 'center', justifyContent: 'center' },
  handle: { width: 48, height: 5, borderRadius: 3, backgroundColor: colors.border },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  aiIcon: { width: 44, height: 44, borderRadius: 16, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' },
  headerCopy: { flex: 1, marginLeft: spacing.sm },
  title: { ...typography.heading, color: colors.textPrimary },
  subtitle: { ...typography.caption, color: colors.textSecondary, marginTop: 2 },
  content: { padding: spacing.lg, paddingBottom: spacing.xl, gap: spacing.md },
  introCard: { flexDirection: 'row', gap: spacing.sm, backgroundColor: colors.primaryLight, padding: spacing.md, borderRadius: 18 },
  introEmoji: { fontSize: 24 },
  introText: { ...typography.body, color: colors.textPrimary, flex: 1 },
  label: { ...typography.caption, color: colors.textPrimary, fontWeight: '800' },
  input: {
    minHeight: 108,
    padding: spacing.md,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.inputBackground,
    color: colors.textPrimary,
    textAlignVertical: 'top',
    ...typography.body,
  },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  chip: { paddingHorizontal: spacing.md, paddingVertical: 10, borderRadius: 999, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  chipActive: { backgroundColor: colors.primaryLight, borderColor: colors.primary },
  chipText: { ...typography.caption, color: colors.textSecondary, fontWeight: '700' },
  chipTextActive: { color: colors.primary },
  primaryButton: { minHeight: 52, borderRadius: 17, backgroundColor: colors.primary, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', paddingHorizontal: spacing.lg },
  primaryButtonText: { color: colors.white, fontSize: 16, fontWeight: '800' },
  disabled: { backgroundColor: colors.disabled },
  error: { ...typography.caption, color: colors.danger, textAlign: 'center' },
  success: { ...typography.caption, color: colors.success, textAlign: 'center', fontWeight: '700' },
  resultHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  resultTitle: { ...typography.heading, color: colors.textPrimary },
  resultSubtitle: { ...typography.caption, color: colors.textSecondary, marginTop: 2 },
  newSearch: { ...typography.caption, color: colors.primary, fontWeight: '800' },
  suggestion: { flexDirection: 'row', gap: spacing.sm, padding: spacing.md, borderRadius: 18, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  suggestionSelected: { borderColor: colors.primary, backgroundColor: colors.primaryLight },
  check: { width: 25, height: 25, borderRadius: 9, borderWidth: 2, borderColor: colors.disabled, alignItems: 'center', justifyContent: 'center' },
  checkSelected: { backgroundColor: colors.primary, borderColor: colors.primary },
  suggestionCopy: { flex: 1, gap: 5 },
  suggestionTitle: { ...typography.body, color: colors.textPrimary, fontWeight: '800' },
  suggestionDescription: { ...typography.caption, color: colors.textSecondary },
  reason: { ...typography.caption, color: colors.primary, marginTop: 3 },
});
