import { StyleSheet } from 'react-native';
import { radii, spacing } from '../../theme/spacing';
import { typography } from '../../theme/typography';
import { shadows } from '../../theme/shadows';

export const createStyles = (colors) => StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: 'transparent' },
  content: { width: '100%', maxWidth: 680, alignSelf: 'center', padding: spacing.lg, gap: spacing.lg },
  title: { ...typography.title, color: colors.textPrimary },
  subtitle: { ...typography.body, color: colors.textSecondary, marginTop: spacing.xs },
  rangePicker: { flexDirection: 'row', padding: 4, borderRadius: radii.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  rangeButton: { flex: 1, minHeight: 42, alignItems: 'center', justifyContent: 'center', borderRadius: 14 },
  rangeButtonActive: { backgroundColor: colors.primary },
  rangeText: { ...typography.label, color: colors.textSecondary },
  rangeTextActive: { color: colors.white },
  heroCard: { ...shadows.card, shadowColor: colors.shadow, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', overflow: 'hidden', padding: spacing.lg, borderRadius: radii.lg, backgroundColor: colors.primary, gap: spacing.sm },
  heroCopy: { flex: 1, minWidth: 0 },
  eyebrow: { ...typography.caption, color: 'rgba(255,255,255,0.72)', fontWeight: '800', letterSpacing: 1 },
  heroPercent: { fontSize: 48, lineHeight: 56, fontWeight: '900', color: colors.white },
  heroCaption: { ...typography.caption, flexShrink: 1, color: 'rgba(255,255,255,0.82)' },
  ring: { width: 88, height: 88, flexShrink: 0, alignItems: 'center', justifyContent: 'center', borderRadius: 44, backgroundColor: 'rgba(255,255,255,0.15)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.25)' },
  ringText: { fontSize: 20 },
  ringValue: { fontSize: 24, lineHeight: 28, fontWeight: '900', color: colors.white },
  ringLabel: { ...typography.caption, color: colors.white },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  statCard: { width: '48.5%', minHeight: 92, justifyContent: 'center', padding: spacing.md, borderRadius: radii.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  statValue: { ...typography.heading, color: colors.textPrimary },
  statLabel: { ...typography.caption, color: colors.textSecondary, marginTop: spacing.xs },
  sectionCard: { ...shadows.card, shadowColor: colors.shadow, padding: spacing.lg, gap: spacing.lg, borderRadius: radii.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  sectionTitle: { ...typography.heading, color: colors.textPrimary },
  chart: { height: 190, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: spacing.xs },
  barColumn: { flex: 1, height: '100%', alignItems: 'center', justifyContent: 'flex-end', gap: spacing.xs },
  barValue: { ...typography.caption, fontSize: 10, color: colors.textSecondary },
  barTrack: { width: '70%', flex: 1, justifyContent: 'flex-end', overflow: 'hidden', borderRadius: 10, backgroundColor: colors.progressTrack },
  barFill: { width: '100%', minHeight: 4, borderRadius: 10, backgroundColor: colors.primary },
  barLabel: { ...typography.caption, color: colors.textSecondary },
  calendarTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm },
  calendarLegend: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  calendarWeekday: { width: '14.2857%', paddingBottom: spacing.sm, textAlign: 'center', ...typography.caption, fontWeight: '800', color: colors.textSecondary },
  calendarDay: { width: '12.5%', aspectRatio: 0.82, margin: '0.8928%', alignItems: 'center', justifyContent: 'center', borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceElevated },
  calendarSpacer: { width: '14.2857%', aspectRatio: 0.9 },
  calendarEmpty: { backgroundColor: colors.progressTrack, borderColor: colors.border },
  calendarPartial: { backgroundColor: colors.primaryLight, borderColor: colors.primary },
  calendarComplete: { backgroundColor: colors.success, borderColor: colors.success },
  calendarDayNumber: { ...typography.label, color: colors.textPrimary },
  calendarCount: { fontSize: 10, lineHeight: 13, fontWeight: '700', color: colors.primary },
  calendarCompleteText: { color: colors.white },
  calendarScale: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm },
  scaleDots: { flexDirection: 'row', gap: spacing.xs },
  legendDot: { width: 12, height: 12, borderRadius: 4, borderWidth: 1 },
  legendText: { ...typography.caption, color: colors.textSecondary },
  habitRow: { gap: spacing.sm },
  habitHeader: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.md },
  habitTitle: { ...typography.label, flex: 1, color: colors.textPrimary },
  habitPercent: { ...typography.label, color: colors.primary },
  progressTrack: { height: 8, overflow: 'hidden', borderRadius: 4, backgroundColor: colors.progressTrack },
  progressFill: { height: '100%', borderRadius: 4, backgroundColor: colors.primary },
  habitCaption: { ...typography.caption, color: colors.textSecondary },
  emptyText: { ...typography.body, color: colors.textSecondary, textAlign: 'center' },
});
