import { StyleSheet } from 'react-native';
import { spacing } from '../../theme/spacing';
import { typography } from '../../theme/typography';

export const createStyles = (colors, isDark) => StyleSheet.create({
  backdrop: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
    backgroundColor: 'rgba(15,17,32,0.68)',
  },
  card: {
    width: '100%',
    maxWidth: 390,
    alignItems: 'center',
    padding: spacing.lg,
    paddingTop: spacing.md,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.surfaceElevated,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.34,
    shadowRadius: 24,
    elevation: 20,
  },
  cat: { width: 245, height: 245 },
  copy: { alignItems: 'center', gap: spacing.xs, marginTop: -spacing.sm },
  title: { ...typography.title, color: isDark ? colors.white : colors.textPrimary, textAlign: 'center' },
  message: { ...typography.body, color: isDark ? colors.white : colors.textSecondary, textAlign: 'center' },
  hint: { ...typography.label, color: isDark ? colors.white : colors.primary, textAlign: 'center', marginTop: spacing.xs },
  claimButton: {
    minWidth: 210,
    minHeight: 54,
    marginTop: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOpacity: 0.28,
    shadowRadius: 10,
    elevation: 7,
  },
  claimButtonPressed: { opacity: 0.78, transform: [{ scale: 0.98 }] },
  claimButtonText: { color: colors.white, fontSize: 17, fontWeight: '900' },
  confetti: { position: 'absolute', color: colors.accent, fontSize: 30, zIndex: 2 },
  confettiLeft: { left: 30, top: 82 },
  confettiRight: { right: 30, top: 115, fontSize: 24 },
  confettiTop: { right: 75, top: 36, fontSize: 25 },
});
